*&---------------------------------------------------------------------*
*&  Include           ZAGTI_SQA_TOOLKIT_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN NESTING LEVEL 2 .
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-s13 .
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-s09 .
SELECTION-SCREEN END OF LINE.
PARAMETERS : p_rb1 RADIOBUTTON GROUP rbg USER-COMMAND f1,
             p_rb2 RADIOBUTTON GROUP rbg,
             p_rb4 RADIOBUTTON GROUP rbg.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-s10.
SELECTION-SCREEN END OF LINE.
PARAMETERS : p_rb5 RADIOBUTTON GROUP rbg,
             p_rb6 RADIOBUTTON GROUP rbg,
             p_rb7 RADIOBUTTON GROUP rbg,
             p_rb8 RADIOBUTTON GROUP rbg.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(20) TEXT-s12.
SELECTION-SCREEN END OF LINE.
PARAMETERS : p_rb9 RADIOBUTTON GROUP rbg.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN END OF SCREEN 200.

SELECTION-SCREEN BEGIN OF SCREEN 300 AS SUBSCREEN NESTING LEVEL 2.
SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-s15.
*PARAMETERS : p_rb10 AS CHECKBOX  DEFAULT abap_true.
PARAMETERS : p_rb10 RADIOBUTTON GROUP rbg1 USER-COMMAND f2,
             p_rb11 RADIOBUTTON GROUP rbg1.
SELECTION-SCREEN END OF BLOCK b3.
SELECTION-SCREEN END OF SCREEN 300.

SELECTION-SCREEN BEGIN OF SCREEN 400 AS SUBSCREEN.
SELECTION-SCREEN END OF SCREEN 400.

SELECTION-SCREEN BEGIN OF SCREEN 500 AS SUBSCREEN.
SELECTION-SCREEN END OF SCREEN 500.

SELECTION-SCREEN BEGIN OF SCREEN 600 AS SUBSCREEN.
SELECTION-SCREEN END OF SCREEN 600.

SELECTION-SCREEN BEGIN OF SCREEN 700 AS SUBSCREEN.
SELECTION-SCREEN END OF SCREEN 700.

SELECTION-SCREEN BEGIN OF SCREEN 800 AS SUBSCREEN.
SELECTION-SCREEN END OF SCREEN 800.

SELECTION-SCREEN BEGIN OF SCREEN 900 AS SUBSCREEN NESTING LEVEL 2.
SELECTION-SCREEN BEGIN OF BLOCK b9 WITH FRAME TITLE TEXT-s16.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(60) TEXT-s17 .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b9.
SELECTION-SCREEN END OF SCREEN 900.
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-s14 .
SELECTION-SCREEN : BEGIN OF TABBED BLOCK tab FOR 20 LINES,
                   TAB (30) tab1  USER-COMMAND push1,
                   TAB (30) tab2  USER-COMMAND push2,
                   TAB (30) tab3  USER-COMMAND push3,
                   TAB (30) tab4  USER-COMMAND push4,
                   TAB (30) tab5  USER-COMMAND push5,
                   TAB (30) tab6  USER-COMMAND push6,
                   TAB (30) tab7  USER-COMMAND push7,
                   TAB (30) tab8  USER-COMMAND push8,
                   END OF BLOCK tab.
SELECTION-SCREEN END OF BLOCK b2.
